---
description: Add compiler security features
diffconfig: |
          CONFIG_DEVEL=y
          CONFIG_JSON_CHECKSEC_MITIGATIONS_REPORT=y
          CONFIG_BUSYBOX_DEFAULT_PIE=y
          CONFIG_GCC_DEFAULT_PIE=y
          CONFIG_KERNEL_CC_STACKPROTECTOR_STRONG=y
          CONFIG_PKG_ASLR_PIE_ALL=y
          CONFIG_PKG_CC_STACKPROTECTOR_STRONG=y
          CONFIG_PKG_FORTIFY_SOURCE_2=y
          CONFIG_TOOLCHAINOPTS=y
